version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: supremecourt_db
      MYSQL_USER: SupremeCourt
      MYSQL_PASSWORD: Xkd4cHg3EvkQBUP6ZweFXunHkJ3EAtz5yvQeKuD7
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: SupremeCourt.Presentation/Dockerfile
    container_name: supremecourt_api
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=supremecourt_db;user=SupremeCourt;password=Xkd4cHg3EvkQBUP6ZweFXunHkJ3EAtz5yvQeKuD7
    ports:
      - "5000:8080"

  frontend:
    build:
      context: SupremeCourt.Presentation.FrontEnd
      dockerfile: Dockerfile
    container_name: supremecourt_frontend
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  mysql_data:
