version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: supremecourt_db
      MYSQL_USER: SupremeCourt
      MYSQL_PASSWORD: PipeMerlin24951411
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    
  api:
    build:
      context: .
      dockerfile: SupremeCourt.Presentation/Dockerfile
    container_name: supremecourt_api
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=supremecourt_db;user=SupremeCourt;password=PipeMerlin24951411
    ports:
      - "5000:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: SupremeCourt.Presentation.FrontEnd
      dockerfile: Dockerfile
    container_name: supremecourt_frontend
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "4200:80"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
